project:
  type: website
  output-dir: docs

website: 
  title: "Moves-UP"
  navbar:
    logo: img/MUlogo.png    # <-- Add your logo path here
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About
      - href: Takingpart.qmd
        text: Taking part
      - href: Research.qmd
        text: Research
      - href: Resources.qmd
        text: Resources
      - href: Impact.qmd
        text: Impact
      - href: Contact.qmd
        text: Contact
     
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/Nils-Swindell/Moves-UP-web-page2
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Nils Swindell"

format:
  html:
    theme: Minty
    toc: true
    css: styles.css

editor: source
execute:
  echo: true
  warning: false
  error: false
  
  
  